export const MessageType = {
  LOGIN_REQUEST: 1,
  LOGIN_RESPONSE: 2,
  MESSAGE_REQUEST: 3,
  MESSAGE_RESPONSE: 4,
  GROUP_CREATE_REQUEST: 5,
  GROUP_CREATE_RESPONSE: 6,
  GROUP_JOIN_REQUEST: 7,
  GROUP_JOIN_RESPONSE: 8,
  GROUP_LIST_REQUEST: 9,
  GROUP_LIST_RESPONSE: 10,
  GROUP_QUIT_REQUEST: 11,
  GROUP_QUIT_RESPONSE: 12,
  GROUP_MESSAGE_REQUEST: 13,
  GROUP_MESSAGE_RESPONSE: 14
}

